import sqlite3
import json
from colorama import Fore, Style, init
from bs4 import BeautifulSoup
import re

# Initialize colorama
init(autoreset=True)

# --- Database Filename Consistency ---
# Make sure this matches the filename used in DataFrame.py
DB_FILENAME = 'game_data_cleaned.db'
# --- Input JSON Filename ---
# Make sure this is the JSON file generated by main.py or the one you intend to process
INPUT_JSON = 'scanned_rawg_games4.json' # Or 'scanned_rawg_games.json', etc.

# Load the JSON data from the file
try:
    # Use the defined input filename
    with open(INPUT_JSON, 'r', encoding='utf-8') as json_file: # Specify UTF-8 on read
        game_data = json.load(json_file)
except FileNotFoundError:
    print(Fore.RED + f"JSON file '{INPUT_JSON}' not found. Make sure it exists.")
    exit(1)
except json.JSONDecodeError:
    print(Fore.RED + f"Error decoding JSON data in '{INPUT_JSON}'. Check the file format.")
    exit(1)
except Exception as e:
    print(Fore.RED + f"An error occurred loading JSON: {e}")
    exit(1)

# Function to clean text data (including descriptions, names, etc.)
def clean_text(text_data):
    if not text_data:
        return text_data # Return None or empty string as is

    # Ensure it's a string
    text_data = str(text_data)

    # Remove HTML tags if any (primarily for description)
    if '<' in text_data and '>' in text_data: # Basic check to avoid unnecessary parsing
        try:
            soup = BeautifulSoup(text_data, 'html.parser')
            text_data = soup.get_text()
        except Exception:
            # If BeautifulSoup fails, proceed with the original text
            pass

    # REMOVED the problematic re.sub line: text_data = re.sub(r'[]', '', text_data)

    # Force encoding to UTF-8, ignoring errors
    # This is the key step to remove problematic bytes like 0xae
    try:
        # Option 1: Ignore errors (removes the character) - Recommended
        text_data = text_data.encode('utf-8', 'ignore').decode('utf-8')
        # Option 2: Replace errors (replaces char with '?') - Uncomment if preferred
        # text_data = text_data.encode('utf-8', 'replace').decode('utf-8')
    except Exception:
        # Fallback if encode/decode fails for some reason
        text_data = re.sub(r'[^\x00-\x7F]+', '', text_data) # Remove non-ASCII as a fallback

    # Remove extra whitespace and newlines
    text_data = re.sub(r'\s+', ' ', text_data).strip()

    return text_data

# Initialize a list to store the extracted data
extracted_data = []

# Extract the specified fields for all games
print(f"Processing {len(game_data)} games...")
for index, game in enumerate(game_data, start=1):
    # Apply clean_text to all potentially problematic string fields
    game_id = game.get('id')
    game_slug = clean_text(game.get('slug'))
    game_name = clean_text(game.get('name'))
    game_released = game.get('released') # Dates are usually safe
    game_year = game_released.split('-')[0] if game_released else None
    game_background_image = game.get('background_image') # URLs are usually safe
    game_rating = game.get('rating', None)
    game_metacritic = game.get('metacritic', None)
    game_playtime = game.get('playtime', None)

    # Extract and clean parent platforms
    parent_platforms = game.get('parent_platforms', [])
    game_parent_platforms_list = [clean_text(platform['platform']['name']) for platform in parent_platforms if 'platform' in platform and 'name' in platform['platform']]
    game_parent_platforms = ', '.join(filter(None, game_parent_platforms_list)) # Filter out None results from cleaning

    # Extract and clean genres
    genres = game.get('genres', [])
    game_genres_list = [clean_text(genre['name']) for genre in genres if 'name' in genre]
    game_genres = ', '.join(filter(None, game_genres_list)) # Filter out None results

    # Clean the description
    game_description = clean_text(game.get('description'))

    # Create a dictionary with the extracted data for this game
    game_info = {
        "Index": index,
        "ID": game_id,
        "Slug": game_slug,
        "Name": game_name,
        "Date Released": game_released,
        "Year Released": game_year,
        "Background Image": game_background_image,
        "Rating": game_rating,
        "Metacritic": game_metacritic,
        "Playtime": game_playtime,
        "Platforms": game_parent_platforms,
        "Genres": game_genres,
        "Description": game_description,
    }

    # Append the game data to the list
    extracted_data.append(game_info)

# (Optional) Print the extracted data with a box-like border - can be slow for many games
# Consider printing only the first few or removing this section for large datasets
# print("Sample processed data:")
# for game_info in extracted_data[:5]: # Print only first 5
#     index_str = str(game_info['Index'])
#     # ... (rest of the printing code - keep as is or remove/comment out) ...
#     print(f"Description: {game_info['Description'][:100]}...") # Print truncated description
#     print("\n")

# SQLite database setup
# Use the defined DB filename
conn = sqlite3.connect(DB_FILENAME)
cursor = conn.cursor()

# Create a games table if it doesn't exist
# Ensure column types match the cleaned data (TEXT for most cleaned fields)
cursor.execute('''
    CREATE TABLE IF NOT EXISTS games (
        id INTEGER PRIMARY KEY,
        slug TEXT,
        name TEXT,
        datereleased TEXT,
        yearreleased TEXT,
        background_image TEXT,
        rating REAL,
        metacritic INTEGER,
        playtime INTEGER,
        platforms TEXT,
        genres TEXT,
        description TEXT
    )
''')

# Drop existing data if you want a fresh import (optional)
# print(f"Deleting existing data from table 'games' in {DB_FILENAME}...")
# cursor.execute('DELETE FROM games')

# Insert data into the games table
print(f"Inserting {len(extracted_data)} records into {DB_FILENAME}...")
for game_info in extracted_data:
    try:
        cursor.execute('''
            INSERT OR IGNORE INTO games (
                id, slug, name, datereleased, yearreleased, background_image, rating, metacritic, playtime, platforms,
                genres, description
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            game_info['ID'],
            game_info['Slug'],
            game_info['Name'],
            game_info['Date Released'],
            game_info['Year Released'],
            game_info['Background Image'],
            game_info['Rating'],
            game_info['Metacritic'],
            game_info['Playtime'],
            game_info['Platforms'],
            game_info['Genres'],
            game_info['Description'],
        ))
    except sqlite3.InterfaceError as e:
        print(f"Error inserting game ID {game_info['ID']}: {e}")
        print(f"Problematic data: {game_info}")
        # Decide how to handle errors: skip, log, etc.
        continue # Skip this record

# Commit the changes and close the database connection
conn.commit()
conn.close()

print(Fore.GREEN + f"Data successfully processed and inserted into '{DB_FILENAME}'.")

